### ISSUE TITLE
Update microtime dependency

### ISSUE THREAD

**Issue by nwinch** [brianreavis/sifter.js#17]
I'm getting errors when installing with Node `0.11.x`.

> npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sifter" "--save"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! microtime@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@0.5.1 install script.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

Could you add support for a later version of `microtime`?  The author seems to have added support for `0.11.x`:
https://github.com/wadey/node-microtime/issues/19

**Comment by damianbaar** [comment]
+1

**Comment by brianreavis** [comment]
Updated: [0.4.1](https://github.com/brianreavis/sifter.js/releases/tag/v0.4.1)
