### ISSUE TITLE
Node-csv Dependency

### ISSUE THREAD

**Issue by OrKoN** [brianreavis/sifter.js#18]
Hi,

I have a problem loading Siffer.js with jspm because jspm does not support loading dependencies from a tarball/archive (https://github.com/jspm/jspm-cli/issues/424). Although it's the issue of jspm, I wonder why the dependency on node-csv is specified as "https://github.com/voodootikigod/node-csv/tarball/master". Is it possible to change this to "git://github.com/voodootikigod/node-csv". Please see the pull request (https://github.com/brianreavis/sifter.js/pull/19).

Thanks in advance!

Best regards,
Alex

**Comment by noBlubb** [comment]
+1
