### ISSUE TITLE
Unable to install due to firewall, because hard coded dependency

### ISSUE THREAD

**Issue by murm** [brianreavis/sifter.js#39]
Hi!

I am unable to install at all, because of the hard coded dependency of node-csv ("node-csv": "https://github.com/voodootikigod/node-csv/tarball/master").

Edit: I can't configure a proxy, I use a custom registry which can't handle hard coded urls

Best regards,
murm

**Comment by brianreavis** [comment]
Closed by https://github.com/brianreavis/sifter.js/pull/45
