### ISSUE TITLE
Possible MITM Vulnerability in node-csv dependency

### ISSUE THREAD

**Issue by rliota** [brianreavis/sifter.js#43]
Hi - first off I'd like to thank you for this library. 
I noticed (just today) in checking out the latest patch version of selectize 0.12.2 that this project's node-csv dependency access protocol changed from https to git a while ago.

Is there a specific reason for the change to git: instead of the authenticated https protocol?
I've read both https://github.com/brianreavis/sifter.js/issues/18 and https://github.com/brianreavis/sifter.js/pull/19 and I still don't understand why the protocol was changed.

Can it be changed back to https?

**Comment by skeggse** [comment]
Alternatively, one could use `git+ssh://`

**Comment by sbabrass** [comment]
Using `git:` also breaks the `npm install` command for me. Throws error `Connection refused`. Using `git+ssh://` solves this issue for me. I am opening a pull request.

**Comment by brianreavis** [comment]
Closed by https://github.com/brianreavis/sifter.js/pull/45
